// <auto-generated />
namespace CSharpRest.Domain.Migrations.SongSetup
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SetupSong : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetupSong));
        
        string IMigrationMetadata.Id
        {
            get { return "201712121948462_SetupSong"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
