// <auto-generated />
namespace CSharpRest.Domain.Migrations.Setup
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SetupAlbumMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetupAlbumMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201712112107416_SetupAlbumMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
